### ISSUE TITLE
错字：阶乘不是界乘

### ISSUE THREAD

**Issue by zouhangwithsweet** [Q-Angelo/Nodejs-Roadmap#48]
![image](https://user-images.githubusercontent.com/21095710/60795564-76b52b00-a19e-11e9-9a5b-c1d9d16fe300.png)

**Comment by zouhangwithsweet** [comment]
![image](https://user-images.githubusercontent.com/21095710/60795880-0f4bab00-a19f-11e9-9993-a657ecd5f2b8.png)
说反了

**Comment by zouhangwithsweet** [comment]
![image](https://user-images.githubusercontent.com/21095710/60797461-db25b980-a1a1-11e9-9ca3-5792b851f5dc.png)
说反了

**Comment by Q-Angelo** [comment]
谢谢提出，已修正！
