### ISSUE TITLE
createCipheriv替换createCipher

### ISSUE THREAD

**Issue by WxSwen** [Q-Angelo/Nodejs-Roadmap#73]
crypto加解密模块一章：
crypto.createCipher好像被废弃了，
![image](https://user-images.githubusercontent.com/20021502/67062741-d4421600-f196-11e9-9de7-46ef65fcaa8c.png)

**Comment by Q-Angelo** [comment]
@WxSwen 是的，createCipher 不支持向量通常也会使用 createCipheriv，谢谢关注提出，我标注下。
